networks:
  tor_net:
    ipam:
      config:
        - subnet: 172.20.0.0/16

services:
  tor:
    image: docker.io/nikhilch/tor:latest
    ports:
      - "9050:9050"
    expose:
      - "53/udp"
    networks:
      tor_net:
        ipv4_address: 172.20.0.5
    restart: unless-stopped

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - USER=admin
      - PASS=password #Change me
    volumes:
      - ./transmission-config:/config
      - ./:/downloads
      - ./incomplete:/incomplete
      - ./torrents:/watch
    ports:
      - "9091:9091"
    dns:
      - 172.20.0.5 # Points directly to Tor's DNSPort
    networks:
      - tor_net
    depends_on:
      - tor
    restart: unless-stopped
